## Problema de la mochila 

En algoritmia, el problema de la mochila, es un problema de optimización combinatoria, es decir, que busca la mejor solución entre un conjunto finito de posibles soluciones a un problema. Modela una situación análoga al llenar una mochila, incapaz de soportar más de un peso determinado, con todo o parte de un conjunto de objetos, cada uno con un peso y valor específicos. Los objetos colocados en la mochila deben maximizar el valor total sin exceder el peso máximo.<br>

Para este ejemplo utilizaremos el metodo conocido como el del mayor indice.Tambien cabe recalcar que no es fraccionario,es decir no se puede meter la mitad de un objeto.
Este metodo trata de dividir el valor por peso, para asi obtener el indice.


In [7]:
import numpy as np
n = int(input('Ingrese el numero de elementos que desea ingresar: ')) #Ingresar tamaño del array 
elemento = []
vector=np.array(elemento)
#Pedimos el numero elemento con peso y valor 
for i in range(n):
    valor = int(input('ingrese el peso: '))
    peso = int(input('ingrese el valor: '))
    indice = valor/peso 
    elemento.append([valor,peso,indice]) #Agramos los valores al array
vector=np.array(elemento)
vector = np.sort(vector, axis=0) #Ordenamos el aray de menor a mayor
vectores_ordenados = vector[::-1] #Invertimos el orden del array para que quede de mayor a menor 
print(vectores_ordenados)



Ingrese el numero de elementos que desea ingresar: 5
ingrese el peso: 80
ingrese el valor: 5
ingrese el peso: 50
ingrese el valor: 10
ingrese el peso: 6
ingrese el valor: 2
ingrese el peso: 50
ingrese el valor: 2
ingrese el peso: 30
ingrese el valor: 10
[[80. 10. 25.]
 [50. 10. 16.]
 [50.  5.  5.]
 [30.  2.  3.]
 [ 6.  2.  3.]]


In [8]:
suma_pesos = 0
peso_max = int(input('Ingrese el capacidad maxima de la mochila: '))
suma_pesos = vectores_ordenados[0,0:1] + suma_pesos
for i in range(n):
     if suma_pesos <= peso_max:       
            suma_pesos = vectores_ordenados[i+1,0:1] + suma_pesos
            if suma_pesos >= peso_max:
                print('peso total' ,suma_pesos - vectores_ordenados[i+1,0:1])
            else:
                print('peso maximo',suma_pesos , i+1)


Ingrese el capacidad maxima de la mochila: 150
peso maximo [130.] 1
peso total [130.]
