## Manual
### Tema 2: Principios basicos del aprendizaje automatico con Python.

<h3><b>Librerias que ocuparemos:<b></h3> <br>
 Librerias de calculo matricial 
    <ul>
    <li>Numpy</li>
    <li>Scipy</li>
    </ul>
    
 Tratamiento de datos 
    <ul>
    <li>Pandas</li>
    <li>Blaze</li>
    </ul>
    
 Analisis estadistico y machine learning
    <ul>
    <li>Statsmodels</li>
    <li>scikit learn for beginners</li>
    </ul>

  Visualizacion
    <ul>
    <li>Matplolib</li>
    <li>Bokeh</li>
    </ul>
    
  Analisis estadistico y machine learning
    <ul>
    <li>Scrapy</li>
    <li>Networkx-Igraph</li>
    <li>Re</li>
    </ul>



## Trabjando con NumPy

In [82]:
import numpy as np  #Importamos la libreria de numpy 
print('Version de numpy = > ' , np.__version__) #Comprobar la version de numpy importada

a = np.array([[0,1,2,3], [4,5,6,7],[8,9,10,11]])
rows, cols = np.shape(a)
print('filas : {} ; columans:{}'.format(rows, cols))
print(a)

print('Diagonal', np.diag(a))# Imprime la diagonal de matriz

Version de numpy = >  1.18.1
filas : 3 ; columans:4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Diagonal [ 0  5 10]


In [83]:
#Vctores con numeros complejos (complex numbers)
b = np.array([[2,3],[6,7]], dtype=np.complex64)
print(b)

[[2.+0.j 3.+0.j]
 [6.+0.j 7.+0.j]]


In [84]:
#Inicializando  vectores 
np.zeros((3,5)) #Retorna un array con ceros // El primer primer numero sera el numeor de filas y el segundo el numero de columnas


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.zeros_like(b) #retorna un array simolar al dado pero con ceros

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [86]:
np.empty([2,3]) #La función empty se utiliza para crear una nueva matriz sin inicializar entradas.

array([[0.0e+000, 2.5e-323, 4.9e-324],
       [0.0e+000, 4.9e-324, 2.0e-323]])

In [87]:
np.eye(5) #Devuelve una matriz con unos en la diagonal y ceros en los demas lugares

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
#arange => devuelve un array con valores dentro del intervalo dado. 
#diag => construye una matriz diagonal. 
np.diag(np.arange(5)) 

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [89]:
np.arange(6) #arange => devuelve un array con valores dentro del intervalo dado. 

array([0, 1, 2, 3, 4, 5])

In [90]:
np.tile(np.array([[6,7],[8,9]]),(2,5)) # tile =>construye una nueva matriz repitiendo la matriz que le pasamos la cantidad de veces que queramos repetir.

array([[6, 7, 6, 7, 6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9, 8, 9, 8, 9],
       [6, 7, 6, 7, 6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9, 8, 9, 8, 9]])

In [91]:
x = np.arange(50).reshape(5,10) #reshape => ajusta las dismensiones de la estructura 
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [92]:
#construyendo generadores de valores para una matriz 
c =  np.array([[2+i for i in range(5)]  for i in range(4)])
print(c)


[[2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]]


In [93]:
d = np.linspace(0,50,5) #Genera 5  puntos entre 0 y 50
print(d)
print(d[ : ,np.newaxis])#Convertir en un vector de columna

[ 0.  12.5 25.  37.5 50. ]
[[ 0. ]
 [12.5]
 [25. ]
 [37.5]
 [50. ]]


In [94]:
x, y = np.mgrid[0:5,0:5] #Asi se dibiga el grid, las lineas horizontales y verticales 
print(x)
print('--------------')
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
--------------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [95]:
from scipy import sparse
x = np.random.random((2,6))
x[x < 0.85] = 0 # damos un valor cuando los numeros sean menor a 0.85
print(x)
print('----------------------------') 
x_csr = sparse.csr_matrix(x) #Obtemos los valores del resultado con sus posciones
print(x_csr) 
print('-----------------------------') 
print(x_csr.toarray())  #Convierde de nuevo a una matriz

[[0.         0.         0.         0.         0.         0.97789759]
 [0.93313332 0.         0.         0.         0.87424921 0.        ]]
----------------------------
  (0, 5)	0.9778975908949454
  (1, 0)	0.9331333184260726
  (1, 4)	0.8742492074886881
-----------------------------
[[0.         0.         0.         0.         0.         0.97789759]
 [0.93313332 0.         0.         0.         0.87424921 0.        ]]


In [96]:
np.random.seed(125) #Genera numeros aleatorios en base al numero especificado 
np.random.rand(4,4) #Contruye la matriz donde se muestran los numeros aleatorios 

array([[0.50672601, 0.0575307 , 0.62757999, 0.13255253],
       [0.13108515, 0.78854401, 0.50668611, 0.41282608],
       [0.5780087 , 0.48817441, 0.33596388, 0.14081627],
       [0.89144247, 0.08631166, 0.84751223, 0.52961562]])

In [97]:
a = np.array([1.1,1.3,1.4]).astype(int) #Convertimos el tipo de dato de la matris de flotates a enteros
print(a)

a = np.array([1.1,1.3,1.4,1.5,1.6,1.7,1.8,1.9])
b = np.around(a) #Nos ayuda a redondondear los numero de una matriz 
print(b)
b.astype(int) #Convertimos los numeros redoados a integer 

[1 1 1]
[1. 1. 1. 2. 2. 2. 2. 2.]


array([1, 1, 1, 2, 2, 2, 2, 2])

In [98]:
a = np.array([1.0,2.0,3.0])  #Trata vectores de diferentes dimensionces durante la ejecucion de ciertas operaciones
a.astype(int)
b = np.array([2.0,2.0,3.0])
b.astype(int)
d = np.array([1,2,3])


result = a+b #suade de vectores o matrices
result.astype(int) #Convirtiendo el resultado a int

array([3, 4, 6])

In [122]:
#Operaciones de algebra lineal basica

print(x.T)

print('Minimo = ' ,x.min()) #Minamo
print('Maximo  = ' , x.max()) #Maximo 
print('Media Aritmetica = ',x.mean()) #La media aritmetica

print(x.cumsum(1)) 

[[0.         0.93313332]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.87424921]
 [0.97789759 0.        ]]
Minimo =  0.0
Maximo  =  0.9778975908949454
Media Aritmetica =  0.23210667640080884
[[0.         0.         0.         0.         0.         0.97789759]
 [0.93313332 0.93313332 0.93313332 0.93313332 1.80738253 1.80738253]]


In [126]:
print(x*5) #Expresion escalar
print('---------------------')
print(x+3) #suma 3 a cada eleneto de la matriz

[[0.         0.         0.         0.         0.         4.88948795]
 [4.66566659 0.         0.         0.         4.37124604 0.        ]]
---------------------
[[3.         3.         3.         3.         3.         3.97789759]
 [3.93313332 3.         3.         3.         3.87424921 3.        ]]


In [132]:
print(np.dot(x,x.T)) #Esta función devuelve el producto escalar de dos matrices.

[[0.9562837  0.        ]
 [0.         1.63504947]]


<h3>Para el calculo de la determinante y de la matriz inversa hay que incluir la libreria SciPy</h3>
<h5>Formula Determiante (Dimension2x2)</h5>
<img src='https://www.matesfacil.com/matrices/determinantes/D2.png' />

In [145]:
from scipy import linalg # Calculo de la determinante
arr = np.array([[1,2],[3,4]])
print('determinante = ' , linalg.det(arr))

print('matriz inversa = \n',linalg.inv(arr)) #Calcula lla matriz inversa 

determinante =  -2.0
matriz inversa = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [161]:
b = np.array([[2.0,2.0,3.0],
              [4.0,5.0,6.0]])
print(b[1,2]) #Cogiendo elemetos especificos por poscicion 
print(b[-1,-1]) #Cogiendo el ultimo elemento 
print(b[:,2]) #Codgindo elementos fila 0 columna 2

6.0
6.0
[3. 6.]
